import { i18n } from '@/i18n/fund'

const leftAlign = {
    'padding-left': '24px',
    'text-align': 'left',
}
const fixedTitle = [
    {
        title: i18n.t('fcn.productType'),
        key: 'name',
        fixed: true,
        slot: true,
        headSlot: true,
        style: {
            width: `${0.62}rem`,
            'flex-shrink': '0',
            'margin-right': `${0.1}rem`,
        },
    },
    {
        title: i18n.t('fcn.biaodi'),
        key: 'biaodi',
        fixed: true,
        slot: true,
        headSlot: true,
        style: {
            width: `${0.96}rem`,
            'flex-shrink': '0',
        },
    },
]
export const daily = [
    ...fixedTitle,
    {
        title: i18n.t('fcn.annualizedCoupon'),
        key: 'coupon',
        sort: true,
        slot: true,
        style: {
            width: `${0.66 + 0.1}rem`,
            'text-align': 'right',
            'padding-left': '10px',
        },
    },
    {
        title: i18n.t('fcn.strikePrice'),
        key: 'strikePrice',
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.knockOutBid'),
        key: 'knockOutPrice',
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.knockOutObservationFrequency'),
        key: 'knockOutType',
        slot: true,
        style: {
            width: `${0.75 + 0.24}rem`,
            'padding-left': '24px',
            ...leftAlign,
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
    {
        title: i18n.t('fcn.inquiryPeriod'),
        key: 'inquiryPeriod',
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'padding-left': '16px',
            ...leftAlign,
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
    {
        title: i18n.t('currency'),
        key: 'currency',
        slot: true,
        style: {
            width: `${0.4 + 0.16}rem`,
            'padding-left': '16px',
            ...leftAlign,
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
    {
        title: i18n.t('fcn.quotePricer'),
        key: 'pricerName',
        slot: true,
        style: {
            width: `${1.24 + 0.16 + 0.24}rem`,
            'padding-right': '16px',
            ...leftAlign,
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
]
// 历史
export const history = [
    ...fixedTitle,
    {
        title: i18n.t('fcn.annualizedCoupon'),
        key: 'coupon',
        sort: true,
        slot: true,
        style: {
            width: `${0.66 + 0.1}rem`,
            'text-align': 'right',
            'padding-left': '10px',
        },
    },
    {
        title: i18n.t('fcn.strikePrice'),
        key: 'strikePrice',
        sort: true,
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.knockOutBid'),
        key: 'knockOutPrice',
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.facePar'),
        key: 'notePrice',
        sort: true,
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.knockInPrice'),
        key: 'knockInPrice',
        slot: true,
        style: {
            width: `${0.66 + 0.16}rem`,
            'text-align': 'right',
            'padding-left': '16px',
        },
    },
    {
        title: i18n.t('fcn.inquiryPeriod'),
        key: 'inquiryPeriod',
        sort: true,
        slot: true,
        style: {
            width: `${0.58 + 0.2}rem`,
            ...leftAlign,
            'padding-left': '20px',
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
    {
        title: i18n.t('currency'),
        key: 'currency',
        slot: true,
        riseFall: false,
        style: {
            width: `${0.4 + 0.16}rem`,
            ...leftAlign,
            'padding-left': '16px',
        },
        titleItemStyle: {
            'justify-content': 'flex-start',
        },
    },
    {
        title: i18n.t('fcn.time'),
        key: 'inquiryTime',
        sort: true,
        slot: true,
        riseFall: false,
        style: {
            width: `${0.76 + 0.32}rem`,
            'text-align': 'right',
            'padding-left': '16px',
            'padding-right': '16px',
        },
    },
]

export const dailymock = [
    {
        orderId: 83,
        orderNumber: 'STPDE20231128000001',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:30:05',
        inquiryTime: '2023-11-28 19:30:05',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 84,
        orderNumber: 'STPDE20231128000002',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:30:52',
        inquiryTime: '2023-11-28 19:30:52',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 85,
        orderNumber: 'STPDE20231128000003',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:30:53',
        inquiryTime: '2023-11-28 19:30:53',
        pricerName: 'Vontobel',
        strikePrice: null,
        notePrice: null,
        coupon: 101.51,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 86,
        orderNumber: 'STPDE20231128000004',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:30:54',
        inquiryTime: '2023-11-28 19:30:54',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 87,
        orderNumber: 'STPDE20231128000005',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:31:11',
        inquiryTime: '2023-11-28 19:31:11',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 88,
        orderNumber: 'STPDE20231128000006',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:31:38',
        inquiryTime: '2023-11-28 19:31:38',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 89,
        orderNumber: 'STPDE20231128000007',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:34:10',
        inquiryTime: '2023-11-28 19:34:10',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 90,
        orderNumber: 'STPDE20231128000008',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 6,
        inquiryType: 1,
        submitTime: '2023-11-28 19:35:18',
        inquiryTime: '2023-11-28 19:35:18',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 105,
        observationFrequency: 1,
    },
    {
        orderId: 80,
        orderNumber: 'STPDE20231121000006',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'hk', code: '00700' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-21 16:33:45',
        inquiryTime: '2023-11-21 16:33:45',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 92,
        orderNumber: 'STPDE20231128000010',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'sh', code: '000001' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:03:07',
        inquiryTime: '2023-11-28 20:03:07',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 93,
        orderNumber: 'STPDE20231128000011',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'sh', code: '000001' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:03:52',
        inquiryTime: '2023-11-28 20:03:52',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 94,
        orderNumber: 'STPDE20231128000012',
        objectProductType: 1,
        objectCodeList: [{ mkt: 'sh', code: '000002' }],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:04:27',
        inquiryTime: '2023-11-28 20:04:27',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 95,
        orderNumber: 'STPDE20231128000013',
        objectProductType: 1,
        objectCodeList: [
            { mkt: 'sh', code: '000001' },
            { mkt: 'hk', code: '00700' },
            { mkt: 'us', code: 'BABA' },
        ],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:08:32',
        inquiryTime: '2023-11-28 20:08:32',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 96,
        orderNumber: 'STPDE20231128000014',
        objectProductType: 1,
        objectCodeList: [
            { mkt: 'sh', code: '000001' },
            { mkt: 'us', code: 'AMD' },
        ],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:09:20',
        inquiryTime: '2023-11-28 20:09:20',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 97,
        orderNumber: 'STPDE20231128000015',
        objectProductType: 1,
        objectCodeList: [
            { mkt: 'sh', code: '000001' },
            { mkt: 'us', code: 'AMD' },
        ],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:09:55',
        inquiryTime: '2023-11-28 20:09:55',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
    {
        orderId: 98,
        orderNumber: 'STPDE20231128000016',
        objectProductType: 1,
        objectCodeList: [
            { mkt: 'sh', code: '000001' },
            { mkt: 'us', code: 'AMD' },
            { mkt: 'hk', code: '00002' },
        ],
        currency: 'HKD',
        inquiryItem: 2,
        inquiryPeriod: 7,
        inquiryType: 1,
        submitTime: '2023-11-28 20:10:26',
        inquiryTime: '2023-11-28 20:10:26',
        pricerName: '',
        strikePrice: null,
        notePrice: null,
        coupon: null,
        knockOutPrice: 22,
        observationFrequency: 12,
    },
]
