export const countrys = [
    {
        id: 1,
        en: 'Angola',
        zhCn: '安哥拉',
        zhTw: '安哥拉',
        areaCode: '+244',
        countryCode: 'AGO',
        initial: 'agl',
        score: 0,
    },
    {
        id: 2,
        en: 'Afghanistan',
        zhCn: '阿富汗',
        zhTw: '阿富汗',
        areaCode: '+93',
        countryCode: 'AFG',
        initial: 'afh',
        score: 0,
    },
    {
        id: 3,
        en: 'Albania',
        zhCn: '阿尔巴尼亚',
        zhTw: '阿爾巴尼亞',
        areaCode: '+355',
        countryCode: 'ALB',
        initial: 'aebny',
        score: 0,
    },
    {
        id: 4,
        en: 'Algeria',
        zhCn: '阿尔及利亚',
        zhTw: '阿爾及利亞',
        areaCode: '+213',
        countryCode: 'DZA',
        initial: 'aejly',
        score: 0,
    },
    {
        id: 5,
        en: 'Andorra',
        zhCn: '安道尔共和国',
        zhTw: '安道爾共和國',
        areaCode: '+376',
        countryCode: 'AND',
        initial: 'adeghg',
        score: 0,
    },
    {
        id: 6,
        en: 'Anguilla',
        zhCn: '安圭拉岛',
        zhTw: '安圭拉島',
        areaCode: '+1264',
        countryCode: 'AIA',
        initial: 'agld',
        score: 0,
    },
    {
        id: 7,
        en: 'Antigua and Barbuda',
        zhCn: '安提瓜和巴布达',
        zhTw: '安提瓜和巴布達',
        areaCode: '+1268',
        countryCode: 'ATG',
        initial: 'atghbbd',
        score: 0,
    },
    {
        id: 8,
        en: 'Argentina',
        zhCn: '阿根廷',
        zhTw: '阿根廷',
        areaCode: '+54',
        countryCode: 'ARG',
        initial: 'agt',
        score: 0,
    },
    {
        id: 9,
        en: 'Armenia',
        zhCn: '亚美尼亚',
        zhTw: '亞美尼亞',
        areaCode: '+374',
        countryCode: 'ARM',
        initial: 'ymny',
        score: 0,
    },
    {
        id: 10,
        en: 'Australia',
        zhCn: '澳大利亚',
        zhTw: '澳大利亞',
        areaCode: '+61',
        countryCode: 'AUS',
        initial: 'adly',
        score: 0,
    },
    {
        id: 11,
        en: 'Austria',
        zhCn: '奥地利',
        zhTw: '奧地利',
        areaCode: '+43',
        countryCode: 'AUT',
        initial: 'adl',
        score: 0,
    },
    {
        id: 12,
        en: 'Azerbaijan',
        zhCn: '阿塞拜疆',
        zhTw: '阿塞拜疆',
        areaCode: '+994',
        countryCode: 'AZE',
        initial: 'asbj',
        score: 0,
    },
    {
        id: 13,
        en: 'Bahamas',
        zhCn: '巴哈马',
        zhTw: '巴哈馬',
        areaCode: '+1242',
        countryCode: 'BHS',
        initial: 'bhm',
        score: 0,
    },
    {
        id: 14,
        en: 'Bahrain',
        zhCn: '巴林',
        zhTw: '巴林',
        areaCode: '+973',
        countryCode: 'BHR',
        initial: 'bl',
        score: 0,
    },
    {
        id: 15,
        en: 'Bangladesh',
        zhCn: '孟加拉国',
        zhTw: '孟加拉國',
        areaCode: '+880',
        countryCode: 'BGD',
        initial: 'mjlg',
        score: 0,
    },
    {
        id: 16,
        en: 'Barbados',
        zhCn: '巴巴多斯',
        zhTw: '巴巴多斯',
        areaCode: '+1246',
        countryCode: 'BRB',
        initial: 'bbds',
        score: 0,
    },
    {
        id: 17,
        en: 'Belarus',
        zhCn: '白俄罗斯',
        zhTw: '白俄羅斯',
        areaCode: '+375',
        countryCode: 'BLR',
        initial: 'bels',
        score: 0,
    },
    {
        id: 18,
        en: 'Belgium',
        zhCn: '比利时',
        zhTw: '比利時',
        areaCode: '+32',
        countryCode: 'BEL',
        initial: 'bls',
        score: 0,
    },
    {
        id: 19,
        en: 'Belize',
        zhCn: '伯利兹',
        zhTw: '伯利茲',
        areaCode: '+501',
        countryCode: 'BLZ',
        initial: 'blc',
        score: 0,
    },
    {
        id: 20,
        en: 'Benin',
        zhCn: '贝宁',
        zhTw: '貝寧',
        areaCode: '+229',
        countryCode: 'BEN',
        initial: 'bn',
        score: 0,
    },
    {
        id: 21,
        en: 'Bermuda Is.',
        zhCn: '百慕大群岛',
        zhTw: '百慕大群島',
        areaCode: '+1441',
        countryCode: 'BMU',
        initial: 'bmdqd',
        score: 0,
    },
    {
        id: 22,
        en: 'Bolivia',
        zhCn: '玻利维亚',
        zhTw: '玻利維亞',
        areaCode: '+591',
        countryCode: 'BOL',
        initial: 'blwy',
        score: 0,
    },
    {
        id: 23,
        en: 'Botswana',
        zhCn: '博茨瓦纳',
        zhTw: '博茨瓦納',
        areaCode: '+267',
        countryCode: 'BWA',
        initial: 'bcwn',
        score: 0,
    },
    {
        id: 24,
        en: 'Brazil',
        zhCn: '巴西',
        zhTw: '巴西',
        areaCode: '+55',
        countryCode: 'BRA',
        initial: 'bx',
        score: 0,
    },
    {
        id: 25,
        en: 'Brunei',
        zhCn: '文莱',
        zhTw: '文萊',
        areaCode: '+673',
        countryCode: 'BRN',
        initial: 'wl',
        score: 0,
    },
    {
        id: 26,
        en: 'Bulgaria',
        zhCn: '保加利亚',
        zhTw: '保加利亞',
        areaCode: '+359',
        countryCode: 'BGR',
        initial: 'bjly',
        score: 0,
    },
    {
        id: 27,
        en: 'Burkinafaso',
        zhCn: '布基纳法索',
        zhTw: '布基納法索',
        areaCode: '+226',
        countryCode: 'BFA',
        initial: 'bjnfs',
        score: 0,
    },
    {
        id: 28,
        en: 'Burma',
        zhCn: '缅甸',
        zhTw: '緬甸',
        areaCode: '+95',
        countryCode: 'MMR',
        initial: 'md',
        score: 0,
    },
    {
        id: 29,
        en: 'Burundi',
        zhCn: '布隆迪',
        zhTw: '布隆迪',
        areaCode: '+257',
        countryCode: 'BDI',
        initial: 'bld',
        score: 0,
    },
    {
        id: 30,
        en: 'Cameroon',
        zhCn: '喀麦隆',
        zhTw: '喀麥隆',
        areaCode: '+237',
        countryCode: 'CMR',
        initial: 'kml',
        score: 0,
    },
    {
        id: 31,
        en: 'Canada',
        zhCn: '加拿大',
        zhTw: '加拿大',
        areaCode: '+1',
        countryCode: 'CAN',
        initial: 'jnd',
        score: 0,
    },
    {
        id: 32,
        en: 'Cayman Is.',
        zhCn: '开曼群岛',
        zhTw: '開曼群島',
        areaCode: '+1345',
        countryCode: 'CYM',
        initial: 'kmqd',
        score: 0,
    },
    {
        id: 33,
        en: 'Central African Republic',
        zhCn: '中非共和国',
        zhTw: '中非共和國',
        areaCode: '+236',
        countryCode: 'CAF',
        initial: 'zfghg',
        score: 0,
    },
    {
        id: 34,
        en: 'Chad',
        zhCn: '乍得',
        zhTw: '乍得',
        areaCode: '+235',
        countryCode: 'TCD',
        initial: 'zd',
        score: 0,
    },
    {
        id: 35,
        en: 'Chile',
        zhCn: '智利',
        zhTw: '智利',
        areaCode: '+56',
        countryCode: 'CHL',
        initial: 'zl',
        score: 0,
    },
    {
        id: 36,
        en: 'China',
        zhCn: '中国大陆',
        zhTw: '中國大陸',
        areaCode: '+86',
        countryCode: 'CHN',
        initial: 'zgdl',
        score: 100,
    },
    {
        id: 37,
        en: 'Colombia',
        zhCn: '哥伦比亚',
        zhTw: '哥倫比亞',
        areaCode: '+57',
        countryCode: 'COL',
        initial: 'glby',
        score: 0,
    },
    {
        id: 38,
        en: 'Congo',
        zhCn: '刚果',
        zhTw: '剛果',
        areaCode: '+242',
        countryCode: 'COG',
        initial: 'gg',
        score: 0,
    },
    {
        id: 39,
        en: 'Cook Is.',
        zhCn: '库克群岛',
        zhTw: '庫克群島',
        areaCode: '+682',
        countryCode: 'COK',
        initial: 'kkqd',
        score: 0,
    },
    {
        id: 40,
        en: 'Costa Rica',
        zhCn: '哥斯达黎加',
        zhTw: '哥斯達黎加',
        areaCode: '+506',
        countryCode: 'CRI',
        initial: 'gsdlj',
        score: 0,
    },
    {
        id: 41,
        en: 'Cuba',
        zhCn: '古巴',
        zhTw: '古巴',
        areaCode: '+53',
        countryCode: 'CUB',
        initial: 'gb',
        score: 0,
    },
    {
        id: 42,
        en: 'Cyprus',
        zhCn: '塞浦路斯',
        zhTw: '塞浦路斯',
        areaCode: '+357',
        countryCode: 'CYP',
        initial: 'spls',
        score: 0,
    },
    {
        id: 43,
        en: 'Czech Republic',
        zhCn: '捷克',
        zhTw: '捷克',
        areaCode: '+420',
        countryCode: 'CZE',
        initial: 'jk',
        score: 0,
    },
    {
        id: 44,
        en: 'Denmark',
        zhCn: '丹麦',
        zhTw: '丹麥',
        areaCode: '+45',
        countryCode: 'DNK',
        initial: 'dm',
        score: 0,
    },
    {
        id: 45,
        en: 'Djibouti',
        zhCn: '吉布提',
        zhTw: '吉布提',
        areaCode: '+253',
        countryCode: 'DJI',
        initial: 'jbt',
        score: 0,
    },
    {
        id: 46,
        en: 'Dominica Rep.',
        zhCn: '多米尼加共和国',
        zhTw: '多米尼加共和國',
        areaCode: '+1890',
        countryCode: 'DOM',
        initial: 'dmnjghg',
        score: 0,
    },
    {
        id: 47,
        en: 'Ecuador',
        zhCn: '厄瓜多尔',
        zhTw: '厄瓜多爾',
        areaCode: '+593',
        countryCode: 'ECU',
        initial: 'egde',
        score: 0,
    },
    {
        id: 48,
        en: 'Egypt',
        zhCn: '埃及',
        zhTw: '埃及',
        areaCode: '+20',
        countryCode: 'EGY',
        initial: 'aj',
        score: 0,
    },
    {
        id: 49,
        en: 'EI Salvador',
        zhCn: '萨尔瓦多',
        zhTw: '薩爾瓦多',
        areaCode: '+503',
        countryCode: 'SLV',
        initial: 'sewd',
        score: 0,
    },
    {
        id: 50,
        en: 'Estonia',
        zhCn: '爱沙尼亚',
        zhTw: '愛沙尼亞',
        areaCode: '+372',
        countryCode: 'EST',
        initial: 'asny',
        score: 0,
    },
    {
        id: 51,
        en: 'Ethiopia',
        zhCn: '埃塞俄比亚',
        zhTw: '埃塞俄比亞',
        areaCode: '+251',
        countryCode: 'ETH',
        initial: 'aseby',
        score: 0,
    },
    {
        id: 52,
        en: 'Fiji',
        zhCn: '斐济',
        zhTw: '斐濟',
        areaCode: '+679',
        countryCode: 'FJI',
        initial: 'fj',
        score: 0,
    },
    {
        id: 53,
        en: 'Finland',
        zhCn: '芬兰',
        zhTw: '芬蘭',
        areaCode: '+358',
        countryCode: 'FIN',
        initial: 'fl',
        score: 0,
    },
    {
        id: 54,
        en: 'France',
        zhCn: '法国',
        zhTw: '法國',
        areaCode: '+33',
        countryCode: 'FRA',
        initial: 'fg',
        score: 0,
    },
    {
        id: 55,
        en: 'French Guiana',
        zhCn: '法属圭亚那',
        zhTw: '法屬圭亞那',
        areaCode: '+594',
        countryCode: 'GUF',
        initial: 'fsgyn',
        score: 0,
    },
    {
        id: 56,
        en: 'Gabon',
        zhCn: '加蓬',
        zhTw: '加蓬',
        areaCode: '+241',
        countryCode: 'GAB',
        initial: 'jp',
        score: 0,
    },
    {
        id: 57,
        en: 'Gambia',
        zhCn: '冈比亚',
        zhTw: '岡比亞',
        areaCode: '+220',
        countryCode: 'GMB',
        initial: 'gby',
        score: 0,
    },
    {
        id: 58,
        en: 'Georgia',
        zhCn: '格鲁吉亚',
        zhTw: '格魯吉亞',
        areaCode: '+995',
        countryCode: 'GEO',
        initial: 'gljy',
        score: 0,
    },
    {
        id: 59,
        en: 'Germany',
        zhCn: '德国',
        zhTw: '德國',
        areaCode: '+49',
        countryCode: 'DEU',
        initial: 'dg',
        score: 0,
    },
    {
        id: 60,
        en: 'Ghana',
        zhCn: '加纳',
        zhTw: '加納',
        areaCode: '+233',
        countryCode: 'GHA',
        initial: 'jn',
        score: 0,
    },
    {
        id: 61,
        en: 'Gibraltar',
        zhCn: '直布罗陀',
        zhTw: '直布羅陀',
        areaCode: '+350',
        countryCode: 'GIB',
        initial: 'zblt',
        score: 0,
    },
    {
        id: 62,
        en: 'Greece',
        zhCn: '希腊',
        zhTw: '希臘',
        areaCode: '+30',
        countryCode: 'GRC',
        initial: 'xl',
        score: 0,
    },
    {
        id: 63,
        en: 'Grenada',
        zhCn: '格林纳达',
        zhTw: '格林納達',
        areaCode: '+1809',
        countryCode: 'GRD',
        initial: 'glnd',
        score: 0,
    },
    {
        id: 64,
        en: 'Guam',
        zhCn: '关岛',
        zhTw: '關島',
        areaCode: '+1671',
        countryCode: 'GUM',
        initial: 'gd',
        score: 0,
    },
    {
        id: 65,
        en: 'Guatemala',
        zhCn: '危地马拉',
        zhTw: '危地馬拉',
        areaCode: '+502',
        countryCode: 'GTM',
        initial: 'wdml',
        score: 0,
    },
    {
        id: 66,
        en: 'Guinea',
        zhCn: '几内亚',
        zhTw: '幾內亞',
        areaCode: '+224',
        countryCode: 'GIN',
        initial: 'jny',
        score: 0,
    },
    {
        id: 67,
        en: 'Guyana',
        zhCn: '圭亚那',
        zhTw: '圭亞那',
        areaCode: '+592',
        countryCode: 'GUY',
        initial: 'gyn',
        score: 0,
    },
    {
        id: 68,
        en: 'Haiti',
        zhCn: '海地',
        zhTw: '海地',
        areaCode: '+509',
        countryCode: 'HTI',
        initial: 'hd',
        score: 0,
    },
    {
        id: 69,
        en: 'Honduras',
        zhCn: '洪都拉斯',
        zhTw: '洪都拉斯',
        areaCode: '+504',
        countryCode: 'HND',
        initial: 'hdls',
        score: 0,
    },
    {
        id: 70,
        en: 'Hongkong',
        zhCn: '中国香港',
        zhTw: '中國香港',
        areaCode: '+852',
        countryCode: 'HKG',
        initial: 'zgxg',
        score: 90,
    },
    {
        id: 71,
        en: 'Hungary',
        zhCn: '匈牙利',
        zhTw: '匈牙利',
        areaCode: '+36',
        countryCode: 'HUN',
        initial: 'xyl',
        score: 0,
    },
    {
        id: 72,
        en: 'Iceland',
        zhCn: '冰岛',
        zhTw: '冰島',
        areaCode: '+354',
        countryCode: 'ISL',
        initial: 'bd',
        score: 0,
    },
    {
        id: 73,
        en: 'India',
        zhCn: '印度',
        zhTw: '印度',
        areaCode: '+91',
        countryCode: 'IND',
        initial: 'yd',
        score: 0,
    },
    {
        id: 74,
        en: 'Indonesia',
        zhCn: '印度尼西亚',
        zhTw: '印度尼西亞',
        areaCode: '+62',
        countryCode: 'IDN',
        initial: 'ydnxy',
        score: 0,
    },
    {
        id: 75,
        en: 'Iran',
        zhCn: '伊朗',
        zhTw: '伊朗',
        areaCode: '+98',
        countryCode: 'IRN',
        initial: 'yl',
        score: 0,
    },
    {
        id: 76,
        en: 'Iraq',
        zhCn: '伊拉克',
        zhTw: '伊拉克',
        areaCode: '+964',
        countryCode: 'IRQ',
        initial: 'ylk',
        score: 0,
    },
    {
        id: 77,
        en: 'Ireland',
        zhCn: '爱尔兰',
        zhTw: '愛爾蘭',
        areaCode: '+353',
        countryCode: 'IRL',
        initial: 'ael',
        score: 0,
    },
    {
        id: 78,
        en: 'Israel',
        zhCn: '以色列',
        zhTw: '以色列',
        areaCode: '+972',
        countryCode: 'ISR',
        initial: 'ysl',
        score: 0,
    },
    {
        id: 79,
        en: 'Italy',
        zhCn: '意大利',
        zhTw: '意大利',
        areaCode: '+39',
        countryCode: 'ITA',
        initial: 'ydl',
        score: 0,
    },
    {
        id: 80,
        en: 'Ivory Coast',
        zhCn: '科特迪瓦',
        zhTw: '科特迪瓦',
        areaCode: '+225',
        countryCode: 'CIV',
        initial: 'ktdw',
        score: 0,
    },
    {
        id: 81,
        en: 'Jamaica',
        zhCn: '牙买加',
        zhTw: '牙買加',
        areaCode: '+1876',
        countryCode: 'JAM',
        initial: 'ymj',
        score: 0,
    },
    {
        id: 82,
        en: 'Japan',
        zhCn: '日本',
        zhTw: '日本',
        areaCode: '+81',
        countryCode: 'JPN',
        initial: 'rb',
        score: 0,
    },
    {
        id: 83,
        en: 'Jordan',
        zhCn: '约旦',
        zhTw: '約旦',
        areaCode: '+962',
        countryCode: 'JOR',
        initial: 'yd',
        score: 0,
    },
    {
        id: 84,
        en: 'Kampuchea (Cambodia )',
        zhCn: '柬埔寨',
        zhTw: '柬埔寨',
        areaCode: '+855',
        countryCode: 'KHM',
        initial: 'jbz',
        score: 0,
    },
    {
        id: 85,
        en: 'Kazakstan',
        zhCn: '哈萨克斯坦',
        zhTw: '哈薩克斯坦',
        areaCode: '+327',
        countryCode: 'KAZ',
        initial: 'hskst',
        score: 0,
    },
    {
        id: 86,
        en: 'Kenya',
        zhCn: '肯尼亚',
        zhTw: '肯尼亞',
        areaCode: '+254',
        countryCode: 'KEN',
        initial: 'kny',
        score: 0,
    },
    {
        id: 87,
        en: 'Korea',
        zhCn: '韩国',
        zhTw: '韓國',
        areaCode: '+82',
        countryCode: 'KOR',
        initial: 'hg',
        score: 0,
    },
    {
        id: 88,
        en: 'Kuwait',
        zhCn: '科威特',
        zhTw: '科威特',
        areaCode: '+965',
        countryCode: 'KWT',
        initial: 'kwt',
        score: 0,
    },
    {
        id: 89,
        en: 'Kyrgyzstan',
        zhCn: '吉尔吉斯坦',
        zhTw: '吉爾吉斯坦',
        areaCode: '+331',
        countryCode: 'KGZ',
        initial: 'jejst',
        score: 0,
    },
    {
        id: 90,
        en: 'Laos',
        zhCn: '老挝',
        zhTw: '老撾',
        areaCode: '+856',
        countryCode: 'LAO',
        initial: 'lw',
        score: 0,
    },
    {
        id: 91,
        en: 'Latvia',
        zhCn: '拉脱维亚',
        zhTw: '拉脫維亞',
        areaCode: '+371',
        countryCode: 'LVA',
        initial: 'ltwy',
        score: 0,
    },
    {
        id: 92,
        en: 'Lebanon',
        zhCn: '黎巴嫩',
        zhTw: '黎巴嫩',
        areaCode: '+961',
        countryCode: 'LBN',
        initial: 'lbn',
        score: 0,
    },
    {
        id: 93,
        en: 'Lesotho',
        zhCn: '莱索托',
        zhTw: '萊索托',
        areaCode: '+266',
        countryCode: 'LSO',
        initial: 'lst',
        score: 0,
    },
    {
        id: 94,
        en: 'Liberia',
        zhCn: '利比里亚',
        zhTw: '利比里亞',
        areaCode: '+231',
        countryCode: 'LBR',
        initial: 'lbly',
        score: 0,
    },
    {
        id: 95,
        en: 'Libya',
        zhCn: '利比亚',
        zhTw: '利比亞',
        areaCode: '+218',
        countryCode: 'LBY',
        initial: 'lby',
        score: 0,
    },
    {
        id: 96,
        en: 'Liechtenstein',
        zhCn: '列支敦士登',
        zhTw: '列支敦士登',
        areaCode: '+423',
        countryCode: 'LIE',
        initial: 'lzdsd',
        score: 0,
    },
    {
        id: 97,
        en: 'Lithuania',
        zhCn: '立陶宛',
        zhTw: '立陶宛',
        areaCode: '+370',
        countryCode: 'LTU',
        initial: 'ltw',
        score: 0,
    },
    {
        id: 98,
        en: 'Luxembourg',
        zhCn: '卢森堡',
        zhTw: '盧森堡',
        areaCode: '+352',
        countryCode: 'LUX',
        initial: 'lsb',
        score: 0,
    },
    {
        id: 99,
        en: 'Macao',
        zhCn: '中国澳门',
        zhTw: '中國澳門',
        areaCode: '+853',
        countryCode: 'MAC',
        initial: 'zgam',
        score: 80,
    },
    {
        id: 100,
        en: 'Madagascar',
        zhCn: '马达加斯加',
        zhTw: '馬達加斯加',
        areaCode: '+261',
        countryCode: 'MDG',
        initial: 'mdjsj',
        score: 0,
    },
    {
        id: 101,
        en: 'Malawi',
        zhCn: '马拉维',
        zhTw: '馬拉維',
        areaCode: '+265',
        countryCode: 'MWI',
        initial: 'mlw',
        score: 0,
    },
    {
        id: 102,
        en: 'Malaysia',
        zhCn: '马来西亚',
        zhTw: '馬來西亞',
        areaCode: '+60',
        countryCode: 'MYS',
        initial: 'mlxy',
        score: 0,
    },
    {
        id: 103,
        en: 'Maldives',
        zhCn: '马尔代夫',
        zhTw: '馬爾代夫',
        areaCode: '+960',
        countryCode: 'MDV',
        initial: 'medf',
        score: 0,
    },
    {
        id: 104,
        en: 'Mali',
        zhCn: '马里',
        zhTw: '馬里',
        areaCode: '+223',
        countryCode: 'MLI',
        initial: 'ml',
        score: 0,
    },
    {
        id: 105,
        en: 'Malta',
        zhCn: '马耳他',
        zhTw: '馬耳他',
        areaCode: '+356',
        countryCode: 'MLT',
        initial: 'met',
        score: 0,
    },
    {
        id: 106,
        en: 'Mariana Is',
        zhCn: '马里亚那群岛',
        zhTw: '馬里亞那群島',
        areaCode: '+1670',
        countryCode: 'MNP',
        initial: 'mlynqd',
        score: 0,
    },
    {
        id: 107,
        en: 'Martinique',
        zhCn: '马提尼克',
        zhTw: '馬提尼克',
        areaCode: '+596',
        countryCode: 'MTQ',
        initial: 'mtnk',
        score: 0,
    },
    {
        id: 108,
        en: 'Mauritius',
        zhCn: '毛里求斯',
        zhTw: '毛里求斯',
        areaCode: '+230',
        countryCode: 'MUS',
        initial: 'mlqs',
        score: 0,
    },
    {
        id: 109,
        en: 'Mexico',
        zhCn: '墨西哥',
        zhTw: '墨西哥',
        areaCode: '+52',
        countryCode: 'MEX',
        initial: 'mxg',
        score: 0,
    },
    {
        id: 110,
        en: 'Moldova, Republic of',
        zhCn: '摩尔多瓦',
        zhTw: '摩爾多瓦',
        areaCode: '+373',
        countryCode: 'MDA',
        initial: 'medw',
        score: 0,
    },
    {
        id: 111,
        en: 'Monaco',
        zhCn: '摩纳哥',
        zhTw: '摩納哥',
        areaCode: '+377',
        countryCode: 'MCO',
        initial: 'mng',
        score: 0,
    },
    {
        id: 112,
        en: 'Mongolia',
        zhCn: '蒙古',
        zhTw: '蒙古',
        areaCode: '+976',
        countryCode: 'MNG',
        initial: 'mg',
        score: 0,
    },
    {
        id: 113,
        en: 'Montserrat Is',
        zhCn: '蒙特塞拉特岛',
        zhTw: '蒙特塞拉特島',
        areaCode: '+1664',
        countryCode: 'MSR',
        initial: 'mtsltd',
        score: 0,
    },
    {
        id: 114,
        en: 'Morocco',
        zhCn: '摩洛哥',
        zhTw: '摩洛哥',
        areaCode: '+212',
        countryCode: 'MAR',
        initial: 'mlg',
        score: 0,
    },
    {
        id: 115,
        en: 'Mozambique',
        zhCn: '莫桑比克',
        zhTw: '莫桑比克',
        areaCode: '+258',
        countryCode: 'MOZ',
        initial: 'msbk',
        score: 0,
    },
    {
        id: 116,
        en: 'Namibia',
        zhCn: '纳米比亚',
        zhTw: '納米比亞',
        areaCode: '+264',
        countryCode: 'NAM',
        initial: 'nmby',
        score: 0,
    },
    {
        id: 117,
        en: 'Nauru',
        zhCn: '瑙鲁',
        zhTw: '瑙魯',
        areaCode: '+674',
        countryCode: 'NRU',
        initial: 'nl',
        score: 0,
    },
    {
        id: 118,
        en: 'Nepal',
        zhCn: '尼泊尔',
        zhTw: '尼泊爾',
        areaCode: '+977',
        countryCode: 'NPL',
        initial: 'npe',
        score: 0,
    },
    {
        id: 119,
        en: 'Netherlands',
        zhCn: '荷兰',
        zhTw: '荷蘭',
        areaCode: '+31',
        countryCode: 'NLD',
        initial: 'hl',
        score: 0,
    },
    {
        id: 120,
        en: 'New Zealand',
        zhCn: '新西兰',
        zhTw: '新西蘭',
        areaCode: '+64',
        countryCode: 'NZL',
        initial: 'xxl',
        score: 0,
    },
    {
        id: 121,
        en: 'Nicaragua',
        zhCn: '尼加拉瓜',
        zhTw: '尼加拉瓜',
        areaCode: '+505',
        countryCode: 'NIC',
        initial: 'njlg',
        score: 0,
    },
    {
        id: 122,
        en: 'Niger',
        zhCn: '尼日尔',
        zhTw: '尼日爾',
        areaCode: '+227',
        countryCode: 'NER',
        initial: 'nre',
        score: 0,
    },
    {
        id: 123,
        en: 'Nigeria',
        zhCn: '尼日利亚',
        zhTw: '尼日利亞',
        areaCode: '+234',
        countryCode: 'NGA',
        initial: 'nrly',
        score: 0,
    },
    {
        id: 124,
        en: 'North Korea',
        zhCn: '朝鲜',
        zhTw: '朝鮮',
        areaCode: '+850',
        countryCode: 'PRK',
        initial: 'zx',
        score: 0,
    },
    {
        id: 125,
        en: 'Norway',
        zhCn: '挪威',
        zhTw: '挪威',
        areaCode: '+47',
        countryCode: 'NOR',
        initial: 'nw',
        score: 0,
    },
    {
        id: 126,
        en: 'Oman',
        zhCn: '阿曼',
        zhTw: '阿曼',
        areaCode: '+968',
        countryCode: 'OMN',
        initial: 'am',
        score: 0,
    },
    {
        id: 127,
        en: 'Pakistan',
        zhCn: '巴基斯坦',
        zhTw: '巴基斯坦',
        areaCode: '+92',
        countryCode: 'PAK',
        initial: 'bjst',
        score: 0,
    },
    {
        id: 128,
        en: 'Panama',
        zhCn: '巴拿马',
        zhTw: '巴拿馬',
        areaCode: '+507',
        countryCode: 'PAN',
        initial: 'bnm',
        score: 0,
    },
    {
        id: 129,
        en: 'Papua New Cuinea',
        zhCn: '巴布亚新几内亚',
        zhTw: '巴布亞新幾內亞',
        areaCode: '+675',
        countryCode: 'PNG',
        initial: 'bbyxjny',
        score: 0,
    },
    {
        id: 130,
        en: 'Paraguay',
        zhCn: '巴拉圭',
        zhTw: '巴拉圭',
        areaCode: '+595',
        countryCode: 'PRY',
        initial: 'blg',
        score: 0,
    },
    {
        id: 131,
        en: 'Peru',
        zhCn: '秘鲁',
        zhTw: '秘魯',
        areaCode: '+51',
        countryCode: 'PER',
        initial: 'ml',
        score: 0,
    },
    {
        id: 132,
        en: 'Philippines',
        zhCn: '菲律宾',
        zhTw: '菲律賓',
        areaCode: '+63',
        countryCode: 'PHL',
        initial: 'flb',
        score: 0,
    },
    {
        id: 133,
        en: 'Poland',
        zhCn: '波兰',
        zhTw: '波蘭',
        areaCode: '+48',
        countryCode: 'POL',
        initial: 'bl',
        score: 0,
    },
    {
        id: 134,
        en: 'French Polynesia',
        zhCn: '法属玻利尼西亚',
        zhTw: '法屬玻利尼西亞',
        areaCode: '+689',
        countryCode: 'PYF',
        initial: 'fsblnxy',
        score: 0,
    },
    {
        id: 135,
        en: 'Portugal',
        zhCn: '葡萄牙',
        zhTw: '葡萄牙',
        areaCode: '+351',
        countryCode: 'PRT',
        initial: 'pty',
        score: 0,
    },
    {
        id: 136,
        en: 'Puerto Rico',
        zhCn: '波多黎各',
        zhTw: '波多黎各',
        areaCode: '+1787',
        countryCode: 'PRI',
        initial: 'bdlg',
        score: 0,
    },
    {
        id: 137,
        en: 'Qatar',
        zhCn: '卡塔尔',
        zhTw: '卡塔爾',
        areaCode: '+974',
        countryCode: 'QAT',
        initial: 'kte',
        score: 0,
    },
    {
        id: 138,
        en: 'Romania',
        zhCn: '罗马尼亚',
        zhTw: '羅馬尼亞',
        areaCode: '+40',
        countryCode: 'ROU',
        initial: 'lmny',
        score: 0,
    },
    {
        id: 139,
        en: 'Russia',
        zhCn: '俄罗斯',
        zhTw: '俄羅斯',
        areaCode: '+7',
        countryCode: 'RUS',
        initial: 'els',
        score: 0,
    },
    {
        id: 140,
        en: 'Samoa Eastern',
        zhCn: '东萨摩亚(美)',
        zhTw: '東薩摩亞(美)',
        areaCode: '+684',
        countryCode: 'ASM',
        initial: 'dsmy(m)',
        score: 0,
    },
    {
        id: 141,
        en: 'Samoa Western',
        zhCn: '西萨摩亚',
        zhTw: '西薩摩亞',
        areaCode: '+685',
        countryCode: 'WSM',
        initial: 'xsmy',
        score: 0,
    },
    {
        id: 142,
        en: 'San Marino',
        zhCn: '圣马力诺',
        zhTw: '聖馬力諾',
        areaCode: '+378',
        countryCode: 'SMR',
        initial: 'smln',
        score: 0,
    },
    {
        id: 143,
        en: 'Sao Tome and Principe',
        zhCn: '圣多美和普林西比',
        zhTw: '聖多美和普林西比',
        areaCode: '+239',
        countryCode: 'STP',
        initial: 'sdmhplxb',
        score: 0,
    },
    {
        id: 144,
        en: 'Saudi Arabia',
        zhCn: '沙特阿拉伯',
        zhTw: '沙特阿拉伯',
        areaCode: '+966',
        countryCode: 'SAU',
        initial: 'stelb',
        score: 0,
    },
    {
        id: 145,
        en: 'Senegal',
        zhCn: '塞内加尔',
        zhTw: '塞內加爾',
        areaCode: '+221',
        countryCode: 'SEN',
        initial: 'snje',
        score: 0,
    },
    {
        id: 146,
        en: 'Seychelles',
        zhCn: '塞舌尔',
        zhTw: '塞舌爾',
        areaCode: '+248',
        countryCode: 'SYC',
        initial: 'sse',
        score: 0,
    },
    {
        id: 147,
        en: 'Sierra Leone',
        zhCn: '塞拉利昂',
        zhTw: '塞拉利昂',
        areaCode: '+232',
        countryCode: 'SLE',
        initial: 'slla',
        score: 0,
    },
    {
        id: 148,
        en: 'Singapore',
        zhCn: '新加坡',
        zhTw: '新加坡',
        areaCode: '+65',
        countryCode: 'SGP',
        initial: 'xjp',
        score: 0,
    },
    {
        id: 149,
        en: 'Slovakia',
        zhCn: '斯洛伐克',
        zhTw: '斯洛伐克',
        areaCode: '+421',
        countryCode: 'SVK',
        initial: 'slfk',
        score: 0,
    },
    {
        id: 150,
        en: 'Slovenia',
        zhCn: '斯洛文尼亚',
        zhTw: '斯洛文尼亞',
        areaCode: '+386',
        countryCode: 'SVN',
        initial: 'slwny',
        score: 0,
    },
    {
        id: 151,
        en: 'Solomon Is',
        zhCn: '所罗门群岛',
        zhTw: '所羅門群島',
        areaCode: '+677',
        countryCode: 'SLB',
        initial: 'slmqd',
        score: 0,
    },
    {
        id: 152,
        en: 'Somali',
        zhCn: '索马里',
        zhTw: '索馬里',
        areaCode: '+252',
        countryCode: 'SOM',
        initial: 'sml',
        score: 0,
    },
    {
        id: 153,
        en: 'South Africa',
        zhCn: '南非',
        zhTw: '南非',
        areaCode: '+27',
        countryCode: 'ZAF',
        initial: 'nf',
        score: 0,
    },
    {
        id: 154,
        en: 'Spain',
        zhCn: '西班牙',
        zhTw: '西班牙',
        areaCode: '+34',
        countryCode: 'ESP',
        initial: 'xby',
        score: 0,
    },
    {
        id: 155,
        en: 'Sri Lanka',
        zhCn: '斯里兰卡',
        zhTw: '斯里蘭卡',
        areaCode: '+94',
        countryCode: 'LKA',
        initial: 'sllk',
        score: 0,
    },
    {
        id: 156,
        en: 'St.Lucia',
        zhCn: '圣卢西亚',
        zhTw: '聖盧西亞',
        areaCode: '+1758',
        countryCode: 'LCA',
        initial: 'slxy',
        score: 0,
    },
    {
        id: 157,
        en: 'St.Vincent',
        zhCn: '圣文森特',
        zhTw: '聖文森特',
        areaCode: '+1784',
        countryCode: 'VCT',
        initial: 'swst',
        score: 0,
    },
    {
        id: 158,
        en: 'Sudan',
        zhCn: '苏丹',
        zhTw: '蘇丹',
        areaCode: '+249',
        countryCode: 'SDN',
        initial: 'sd',
        score: 0,
    },
    {
        id: 159,
        en: 'Suriname',
        zhCn: '苏里南',
        zhTw: '蘇里南',
        areaCode: '+597',
        countryCode: 'SUR',
        initial: 'sln',
        score: 0,
    },
    {
        id: 160,
        en: 'Swaziland',
        zhCn: '斯威士兰',
        zhTw: '斯威士蘭',
        areaCode: '+268',
        countryCode: 'SWZ',
        initial: 'swsl',
        score: 0,
    },
    {
        id: 161,
        en: 'Sweden',
        zhCn: '瑞典',
        zhTw: '瑞典',
        areaCode: '+46',
        countryCode: 'SWE',
        initial: 'rd',
        score: 0,
    },
    {
        id: 162,
        en: 'Switzerland',
        zhCn: '瑞士',
        zhTw: '瑞士',
        areaCode: '+41',
        countryCode: 'CHE',
        initial: 'rs',
        score: 0,
    },
    {
        id: 163,
        en: 'Syria',
        zhCn: '叙利亚',
        zhTw: '敘利亞',
        areaCode: '+963',
        countryCode: 'SYR',
        initial: 'xly',
        score: 0,
    },
    {
        id: 164,
        en: 'Taiwan',
        zhCn: '中国台湾',
        zhTw: '中國台灣',
        areaCode: '+886',
        countryCode: 'TWN',
        initial: 'zgtw',
        score: 70,
    },
    {
        id: 165,
        en: 'Tajikstan',
        zhCn: '塔吉克斯坦',
        zhTw: '塔吉克斯坦',
        areaCode: '+992',
        countryCode: 'TJK',
        initial: 'tjkst',
        score: 0,
    },
    {
        id: 166,
        en: 'Tanzania',
        zhCn: '坦桑尼亚',
        zhTw: '坦桑尼亞',
        areaCode: '+255',
        countryCode: 'TZA',
        initial: 'tsny',
        score: 0,
    },
    {
        id: 167,
        en: 'Thailand',
        zhCn: '泰国',
        zhTw: '泰國',
        areaCode: '+66',
        countryCode: 'THA',
        initial: 'tg',
        score: 0,
    },
    {
        id: 168,
        en: 'Togo',
        zhCn: '多哥',
        zhTw: '多哥',
        areaCode: '+228',
        countryCode: 'TGO',
        initial: 'dg',
        score: 0,
    },
    {
        id: 169,
        en: 'Tonga',
        zhCn: '汤加',
        zhTw: '湯加',
        areaCode: '+676',
        countryCode: 'TON',
        initial: 'tj',
        score: 0,
    },
    {
        id: 170,
        en: 'Trinidad and Tobago',
        zhCn: '特立尼达和多巴哥',
        zhTw: '特立尼達和多巴哥',
        areaCode: '+1809',
        countryCode: 'TTO',
        initial: 'tlndhdbg',
        score: 0,
    },
    {
        id: 171,
        en: 'Tunisia',
        zhCn: '突尼斯',
        zhTw: '突尼斯',
        areaCode: '+216',
        countryCode: 'TUN',
        initial: 'tns',
        score: 0,
    },
    {
        id: 172,
        en: 'Turkey',
        zhCn: '土耳其',
        zhTw: '土耳其',
        areaCode: '+90',
        countryCode: 'TUR',
        initial: 'teq',
        score: 0,
    },
    {
        id: 173,
        en: 'Turkmenistan',
        zhCn: '土库曼斯坦',
        zhTw: '土庫曼斯坦',
        areaCode: '+993',
        countryCode: 'TKM',
        initial: 'tkmst',
        score: 0,
    },
    {
        id: 174,
        en: 'Uganda',
        zhCn: '乌干达',
        zhTw: '烏干達',
        areaCode: '+256',
        countryCode: 'UGA',
        initial: 'wgd',
        score: 0,
    },
    {
        id: 175,
        en: 'Ukraine',
        zhCn: '乌克兰',
        zhTw: '烏克蘭',
        areaCode: '+380',
        countryCode: 'UKR',
        initial: 'wkl',
        score: 0,
    },
    {
        id: 176,
        en: 'United Arab Emirates',
        zhCn: '阿拉伯联合酋长国',
        zhTw: '阿拉伯聯合酋長國',
        areaCode: '+971',
        countryCode: 'ARE',
        initial: 'elblhqcg',
        score: 0,
    },
    {
        id: 177,
        en: 'United Kiongdom',
        zhCn: '英国',
        zhTw: '英國',
        areaCode: '+44',
        countryCode: 'GBR',
        initial: 'yg',
        score: 0,
    },
    {
        id: 178,
        en: 'United States of America',
        zhCn: '美国',
        zhTw: '美國',
        areaCode: '+1',
        countryCode: 'USA',
        initial: 'mg',
        score: 60,
    },
    {
        id: 179,
        en: 'Uruguay',
        zhCn: '乌拉圭',
        zhTw: '烏拉圭',
        areaCode: '+598',
        countryCode: 'URY',
        initial: 'wlg',
        score: 0,
    },
    {
        id: 180,
        en: 'Uzbekistan',
        zhCn: '乌兹别克斯坦',
        zhTw: '烏茲別克斯坦',
        areaCode: '+233',
        countryCode: 'UZB',
        initial: 'wcbkst',
        score: 0,
    },
    {
        id: 181,
        en: 'Venezuela',
        zhCn: '委内瑞拉',
        zhTw: '委內瑞拉',
        areaCode: '+58',
        countryCode: 'VEN',
        initial: 'wnrl',
        score: 0,
    },
    {
        id: 182,
        en: 'Vietnam',
        zhCn: '越南',
        zhTw: '越南',
        areaCode: '+84',
        countryCode: 'VNM',
        initial: 'yn',
        score: 0,
    },
    {
        id: 183,
        en: 'Yemen',
        zhCn: '也门',
        zhTw: '也門',
        areaCode: '+967',
        countryCode: 'YEM',
        initial: 'ym',
        score: 0,
    },
    {
        id: 184,
        en: 'Zimbabwe',
        zhCn: '津巴布韦',
        zhTw: '津巴布韋',
        areaCode: '+263',
        countryCode: 'ZWE',
        initial: 'jbbw',
        score: 0,
    },
    {
        id: 185,
        en: 'Zambia',
        zhCn: '赞比亚',
        zhTw: '贊比亞',
        areaCode: '+260',
        countryCode: 'ZMB',
        initial: 'zby',
        score: 0,
    },
]

export const CountrysObj = countrys.reduce((obj, item) => {
    obj[item.countryCode] = item
    return obj
}, {})
